package com.repcar.user.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.hateoas.ResourceSupport;

/**
 * UserSettings generated by hbm2java
 */
@Entity
@Table(name = "user_settings", catalog = "repcar")
public class UserSettings extends ResourceSupport {

	private Integer userSettingsId;
	private User user;
	private String avatar;
	private String theme;
	private String local;
	private String language;

	public UserSettings() {
	}

	public UserSettings(User user) {
		this.user = user;
	}

	public UserSettings(User user, String avatar, String theme, String local, String language) {
		this.user = user;
		this.avatar = avatar;
		this.theme = theme;
		this.local = local;
		this.language = language;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_settings_id", unique = true, nullable = false)
	public Integer getUserSettingsId() {
		return this.userSettingsId;
	}

	public void setUserSettingsId(Integer userSettingsId) {
		this.userSettingsId = userSettingsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "theme", length = 45)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "local", length = 45)
	public String getLocal() {
		return this.local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
