package com.repcar.user.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * UserSettings generated by hbm2java
 */
@Entity
@Table(name = "user_settings", catalog = "repcar")
public class UserSettings extends ResourceSupport {

	private Integer userSettingsId;
	private String avatar;
	private String theme;
	private String local;
	private String language;

	@JsonCreator
	public UserSettings() {
	}

	@JsonCreator
	public UserSettings(@JsonProperty("avatar") String avatar,
			@JsonProperty("theme") String theme, @JsonProperty("local") String local,
			@JsonProperty("language") String language) {
		this.setAvatar(avatar);
		this.setTheme(theme);
		this.setLocal(local);
		this.setLanguage(language);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_settings_id", unique = true, nullable = false)
	public Integer getUserSettingsId() {
		return this.userSettingsId;
	}

	public void setUserSettingsId(Integer userSettingsId) {
		this.userSettingsId = userSettingsId;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "theme", length = 45)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "local", length = 45)
	public String getLocal() {
		return this.local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
