package com.repcar.user.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.repcar.user.beans.User.Create;
import com.repcar.user.beans.User.Update;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "repcar")
public class UserRole extends ResourceSupport {

	private Integer roleId;
	private String roleName;
	private String roleDescription;

	@JsonCreator
	public UserRole() {
	}

	@JsonCreator
	public UserRole(@JsonProperty("roleName") String roleName,
			@JsonProperty("roleDescription") String roleDescription) {
		this.setRoleName(roleName);
		this.setRoleDescription(roleDescription);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@NotNull(groups = { Create.class, Update.class })
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_description", nullable = false, length = 100)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

}
