/*
 * Copyright RepCar AD 2017
 */
//Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final
package com.repcar.user.beans;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.springframework.hateoas.ResourceSupport;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
* Workshop generated by hbm2java
*/
@Entity
@Table(name = "workshop", catalog = "repcar")
public class Workshop extends ResourceSupport {

	private long workshopId;
	private String workshopName;
	private Set<User> users = new HashSet<User>(0);

	public Workshop() {
	}

	public Workshop(@JsonProperty("workshopName") String workshopName, @JsonProperty("users") Set<User> users) {
		this.workshopName = workshopName;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "workshop_id", unique = true, nullable = false)
	public long getWorkshopId() {
		return this.workshopId;
	}

	public void setWorkshopId(long workshopId) {
		this.workshopId = workshopId;
	}

	@Column(name = "workshop_name", nullable = false, length = 45)
	public String getWorkshopName() {
		return this.workshopName;
	}

	public void setWorkshopName(String workshopName) {
		this.workshopName = workshopName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshop")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((users == null) ? 0 : users.hashCode());
		result = prime * result + (int) (workshopId ^ (workshopId >>> 32));
		result = prime * result + ((workshopName == null) ? 0 : workshopName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (getClass() != obj.getClass())
			return false;
		Workshop other = (Workshop) obj;
		if (users == null) {
			if (other.users != null)
				return false;
		} else if (!users.equals(other.users))
			return false;
		if (workshopId != other.workshopId)
			return false;
		if (workshopName == null) {
			if (other.workshopName != null)
				return false;
		} else if (!workshopName.equals(other.workshopName))
			return false;
		return true;
	}

}