/*
 * Copyright RepCar AD 2017
 */
//Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final
package com.repcar.user.beans;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.hateoas.ResourceSupport;

/**
* Workshop generated by hbm2java
*/
@Entity
@Table(name = "workshop", catalog = "repcar")
public class Workshop extends ResourceSupport {

	private Integer workshopId;
	private String workshopName;
	private Set<User> users = new HashSet<User>(0);

	public Workshop() {
	}

	public Workshop(String workshopName, Set<User> users) {
		this.workshopName = workshopName;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "workshop_id", unique = true, nullable = false)
	public Integer getWorkshopId() {
		return this.workshopId;
	}

	public void setWorkshopId(Integer workshopId) {
		this.workshopId = workshopId;
	}

	@Column(name = "workshop_name", nullable = false, length = 45)
	public String getWorkshopName() {
		return this.workshopName;
	}

	public void setWorkshopName(String workshopName) {
		this.workshopName = workshopName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshop")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}