package com.repcar.security.model;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.repcar.security.model.User;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role", catalog = "repcar")
public class UserRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private String roleDescription;
	private Set<User> users = new HashSet<User>(0);

	public UserRole() {
	}

	public UserRole(String roleName, String roleDescription, Set<User> users) {
		this.roleName = roleName;
		this.roleDescription = roleDescription;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_description", nullable = false, length = 100)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}


}
