package com.repcar.customer.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.hateoas.ResourceSupport;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "car", catalog = "repcar")
public class Car extends ResourceSupport {

	private Integer carId;
	private Workshop workshop;
	private WorkshopCustomer workshopCustomer;
	private String model;
	private int modelYear;
	private String make;

	public Car() {
	}

	public Car(Workshop workshop, WorkshopCustomer workshopCustomer, String model, int modelYear, String make) {
		this.workshop = workshop;
		this.workshopCustomer = workshopCustomer;
		this.model = model;
		this.modelYear = modelYear;
		this.make = make;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workshop_id", nullable = false)
	public Workshop getWorkshop() {
		return this.workshop;
	}

	public void setWorkshop(Workshop workshop) {
		this.workshop = workshop;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public WorkshopCustomer getWorkshopCustomer() {
		return this.workshopCustomer;
	}

	public void setWorkshopCustomer(WorkshopCustomer workshopCustomer) {
		this.workshopCustomer = workshopCustomer;
	}

	@Column(name = "model", nullable = false, length = 50)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "model_year", nullable = false)
	public int getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(int modelYear) {
		this.modelYear = modelYear;
	}

	@Column(name = "make", nullable = false, length = 50)
	public String getMake() {
		return this.make;
	}

	public void setMake(String make) {
		this.make = make;
	}
}
