package com.repcar.customer.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.springframework.hateoas.ResourceSupport;

/**
 * CustomerInvoiceDetails generated by hbm2java
 */
@Entity
@Table(name = "customer_invoice_details", catalog = "repcar")
public class CustomerInvoiceDetails extends ResourceSupport {

	private int invoiceId;
	private WorkshopCustomer workshopCustomer;

	public CustomerInvoiceDetails() {
	}

	public CustomerInvoiceDetails(int invoiceId, WorkshopCustomer workshopCustomer) {
		this.invoiceId = invoiceId;
		this.workshopCustomer = workshopCustomer;
	}

	@Id

	@Column(name = "invoice_id", unique = true, nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public WorkshopCustomer getWorkshopCustomer() {
		return this.workshopCustomer;
	}

	public void setWorkshopCustomer(WorkshopCustomer workshopCustomer) {
		this.workshopCustomer = workshopCustomer;
	}

}
