package com.repcar.customer.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.hateoas.ResourceSupport;

/**
 * WorkshopCustomer generated by hbm2java
 */
@Entity
@Table(name = "workshop_customer", catalog = "repcar")
public class WorkshopCustomer extends ResourceSupport {

	private Integer customerId;
	private Workshop workshop;
	private String email;
	private String telephone;
	private String firstName;
	private String lastName;
	private Date registrationDate;
	private String customerType;
	private String loyalty;
	private String notes;
	private Set<Car> cars = new HashSet<Car>(0);
	private Set<CustomerInvoiceDetails> customerInvoiceDetails = new HashSet<CustomerInvoiceDetails>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public WorkshopCustomer() {
	}

	public WorkshopCustomer(Workshop workshop, String email, String telephone, String firstName, Date registrationDate) {
		this.workshop = workshop;
		this.email = email;
		this.telephone = telephone;
		this.firstName = firstName;
		this.registrationDate = registrationDate;
	}

	public WorkshopCustomer(Workshop workshop, String email, String telephone, String firstName, String lastName,
			Date registrationDate, String customerType, String loyalty, String notes, Set<Car> cars,
			Set<CustomerInvoiceDetails> customerInvoiceDetails, Set<Service> services) {
		this.workshop = workshop;
		this.email = email;
		this.telephone = telephone;
		this.firstName = firstName;
		this.lastName = lastName;
		this.registrationDate = registrationDate;
		this.customerType = customerType;
		this.loyalty = loyalty;
		this.notes = notes;
		this.cars = cars;
		this.customerInvoiceDetails = customerInvoiceDetails;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_id", unique = true, nullable = false)
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workshop_id", nullable = false)
	public Workshop getWorkshop() {
		return this.workshop;
	}

	public void setWorkshop(Workshop workshop) {
		this.workshop = workshop;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "telephone", nullable = false, length = 45)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registration_date", nullable = false, length = 19)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "customer_type", length = 4)
	public String getCustomerType() {
		return this.customerType;
	}

	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}

	@Column(name = "loyalty", length = 45)
	public String getLoyalty() {
		return this.loyalty;
	}

	public void setLoyalty(String loyalty) {
		this.loyalty = loyalty;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopCustomer")
	public Set<Car> getCars() {
		return this.cars;
	}

	public void setCars(Set<Car> cars) {
		this.cars = cars;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopCustomer")
	public Set<CustomerInvoiceDetails> getCustomerInvoiceDetails() {
		return this.customerInvoiceDetails;
	}

	public void setCustomerInvoiceDetails(Set<CustomerInvoiceDetails> customerInvoiceDetails) {
		this.customerInvoiceDetails = customerInvoiceDetails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopCustomer")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
