package com.repcar.makemodel;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientInvoiceDetails generated by hbm2java
 */
@Entity
@Table(name = "client_invoice_details", catalog = "repcar")
public class ClientInvoiceDetails implements java.io.Serializable {

	private int invoiceId;
	private WorkshopClients workshopClients;

	public ClientInvoiceDetails() {
	}

	public ClientInvoiceDetails(int invoiceId, WorkshopClients workshopClients) {
		this.invoiceId = invoiceId;
		this.workshopClients = workshopClients;
	}

	@Id

	@Column(name = "invoice_id", unique = true, nullable = false)
	public int getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(int invoiceId) {
		this.invoiceId = invoiceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	public WorkshopClients getWorkshopClients() {
		return this.workshopClients;
	}

	public void setWorkshopClients(WorkshopClients workshopClients) {
		this.workshopClients = workshopClients;
	}

}
