package com.repcar.makemodel;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OauthRefreshToken generated by hbm2java
 */
@Entity
@Table(name = "oauth_refresh_token", catalog = "repcar")
public class OauthRefreshToken implements java.io.Serializable {

	private String tokenId;
	private byte[] token;
	private byte[] authentication;

	public OauthRefreshToken() {
	}

	public OauthRefreshToken(String tokenId, byte[] token, byte[] authentication) {
		this.tokenId = tokenId;
		this.token = token;
		this.authentication = authentication;
	}

	@Id

	@Column(name = "token_id", unique = true, nullable = false, length = 256)
	public String getTokenId() {
		return this.tokenId;
	}

	public void setTokenId(String tokenId) {
		this.tokenId = tokenId;
	}

	@Column(name = "token", nullable = false)
	public byte[] getToken() {
		return this.token;
	}

	public void setToken(byte[] token) {
		this.token = token;
	}

	@Column(name = "authentication", nullable = false)
	public byte[] getAuthentication() {
		return this.authentication;
	}

	public void setAuthentication(byte[] authentication) {
		this.authentication = authentication;
	}

}
