package com.repcar.customer.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceCategory generated by hbm2java
 */
@Entity
@Table(name = "service_category", catalog = "repcar")
public class ServiceCategory implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Set<UserDefinedService> userDefinedServices = new HashSet<UserDefinedService>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public ServiceCategory() {
	}

	public ServiceCategory(String categoryName, Set<UserDefinedService> userDefinedServices,
			Set<Service> services) {
		this.categoryName = categoryName;
		this.userDefinedServices = userDefinedServices;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceCategory")
	public Set<UserDefinedService> getUserDefinedServices() {
		return this.userDefinedServices;
	}

	public void setUserDefinedServiceses(Set<UserDefinedService> userDefinedServices) {
		this.userDefinedServices = userDefinedServices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceCategories")
	public Set<Service>getServiceses() {
		return this.services;
	}

	public void setServiceses(Set<Service> services) {
		this.services = services;
	}

}
