package com.repcar.makemodel;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "repcar", uniqueConstraints = @UniqueConstraint(columnNames = { "user_name",
		"workshop_id" }))
public class User implements java.io.Serializable {

	private Integer userId;
	private UserRoles userRoles;
	private Workshop workshop;
	private String userName;
	private String userEmail;
	private String userPassword;
	private Date creationDate;
	private String userFirstName;
	private String userLastName;
	private Boolean forcePassChange;
	private String tel;
	private String status;
	private Integer parentUserId;
	private Long companyId;
	private String userAttributes;
	private String userImage;
	private String userRole;
	private Set<WorshopServices> worshopServiceses = new HashSet<WorshopServices>(0);
	private Set<UserSetting> userSettings = new HashSet<UserSetting>(0);

	public User() {
	}

	public User(Workshop workshop, String userName, String userEmail, String userPassword, Date creationDate,
			String userFirstName, String status) {
		this.workshop = workshop;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.creationDate = creationDate;
		this.userFirstName = userFirstName;
		this.status = status;
	}

	public User(UserRoles userRoles, Workshop workshop, String userName, String userEmail, String userPassword,
			Date creationDate, String userFirstName, String userLastName, Boolean forcePassChange, String tel,
			String status, Integer parentUserId, Long companyId, String userAttributes, String userImage,
			String userRole, Set<WorshopServices> worshopServiceses, Set<UserSetting> userSettings) {
		this.userRoles = userRoles;
		this.workshop = workshop;
		this.userName = userName;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.creationDate = creationDate;
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.forcePassChange = forcePassChange;
		this.tel = tel;
		this.status = status;
		this.parentUserId = parentUserId;
		this.companyId = companyId;
		this.userAttributes = userAttributes;
		this.userImage = userImage;
		this.userRole = userRole;
		this.worshopServiceses = worshopServiceses;
		this.userSettings = userSettings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public UserRoles getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(UserRoles userRoles) {
		this.userRoles = userRoles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workshop_id", nullable = false)
	public Workshop getWorkshop() {
		return this.workshop;
	}

	public void setWorkshop(Workshop workshop) {
		this.workshop = workshop;
	}

	@Column(name = "user_name", nullable = false, length = 80)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_email", nullable = false, length = 80)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_password", nullable = false, length = 80)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "user_first_name", nullable = false, length = 45)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "user_last_name", length = 45)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "force_pass_change")
	public Boolean getForcePassChange() {
		return this.forcePassChange;
	}

	public void setForcePassChange(Boolean forcePassChange) {
		this.forcePassChange = forcePassChange;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "status", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "parent_user_id")
	public Integer getParentUserId() {
		return this.parentUserId;
	}

	public void setParentUserId(Integer parentUserId) {
		this.parentUserId = parentUserId;
	}

	@Column(name = "company_id")
	public Long getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(Long companyId) {
		this.companyId = companyId;
	}

	@Column(name = "user_attributes")
	public String getUserAttributes() {
		return this.userAttributes;
	}

	public void setUserAttributes(String userAttributes) {
		this.userAttributes = userAttributes;
	}

	@Column(name = "user_image", length = 45)
	public String getUserImage() {
		return this.userImage;
	}

	public void setUserImage(String userImage) {
		this.userImage = userImage;
	}

	@Column(name = "user_role")
	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<WorshopServices> getWorshopServiceses() {
		return this.worshopServiceses;
	}

	public void setWorshopServiceses(Set<WorshopServices> worshopServiceses) {
		this.worshopServiceses = worshopServiceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserSetting> getUserSettings() {
		return this.userSettings;
	}

	public void setUserSettings(Set<UserSetting> userSettings) {
		this.userSettings = userSettings;
	}

}
