package com.repcar.makemodel;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WorkshopSettings generated by hbm2java
 */
@Entity
@Table(name = "workshop_settings", catalog = "repcar")
public class WorkshopSettings implements java.io.Serializable {

	private Integer settingsId;
	private Workshop workshop;
	private String workshopLogo;

	public WorkshopSettings() {
	}

	public WorkshopSettings(Workshop workshop) {
		this.workshop = workshop;
	}

	public WorkshopSettings(Workshop workshop, String workshopLogo) {
		this.workshop = workshop;
		this.workshopLogo = workshopLogo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "settings_id", unique = true, nullable = false)
	public Integer getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(Integer settingsId) {
		this.settingsId = settingsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "worshop_id", nullable = false)
	public Workshop getWorkshop() {
		return this.workshop;
	}

	public void setWorkshop(Workshop workshop) {
		this.workshop = workshop;
	}

	@Column(name = "workshop_logo", length = 45)
	public String getWorkshopLogo() {
		return this.workshopLogo;
	}

	public void setWorkshopLogo(String workshopLogo) {
		this.workshopLogo = workshopLogo;
	}

}
