package com.repcar.makemodel;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkshopClients generated by hbm2java
 */
@Entity
@Table(name = "workshop_clients", catalog = "repcar")
public class WorkshopClients implements java.io.Serializable {

	private Integer clientId;
	private Workshop workshop;
	private String email;
	private String tel;
	private String firstName;
	private String lastName;
	private Date registrationDate;
	private String clientType;
	private String loyalClient;
	private String notes;
	private Set<Cars> carses = new HashSet<Cars>(0);
	private Set<ClientInvoiceDetails> clientInvoiceDetailses = new HashSet<ClientInvoiceDetails>(0);
	private Set<WorshopServices> worshopServiceses = new HashSet<WorshopServices>(0);

	public WorkshopClients() {
	}

	public WorkshopClients(Workshop workshop, String email, String tel, String firstName, Date registrationDate) {
		this.workshop = workshop;
		this.email = email;
		this.tel = tel;
		this.firstName = firstName;
		this.registrationDate = registrationDate;
	}

	public WorkshopClients(Workshop workshop, String email, String tel, String firstName, String lastName,
			Date registrationDate, String clientType, String loyalClient, String notes, Set<Cars> carses,
			Set<ClientInvoiceDetails> clientInvoiceDetailses, Set<WorshopServices> worshopServiceses) {
		this.workshop = workshop;
		this.email = email;
		this.tel = tel;
		this.firstName = firstName;
		this.lastName = lastName;
		this.registrationDate = registrationDate;
		this.clientType = clientType;
		this.loyalClient = loyalClient;
		this.notes = notes;
		this.carses = carses;
		this.clientInvoiceDetailses = clientInvoiceDetailses;
		this.worshopServiceses = worshopServiceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_id", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "workshop_id", nullable = false)
	public Workshop getWorkshop() {
		return this.workshop;
	}

	public void setWorkshop(Workshop workshop) {
		this.workshop = workshop;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "tel", nullable = false, length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "registration_date", nullable = false, length = 19)
	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(Date registrationDate) {
		this.registrationDate = registrationDate;
	}

	@Column(name = "client_type", length = 4)
	public String getClientType() {
		return this.clientType;
	}

	public void setClientType(String clientType) {
		this.clientType = clientType;
	}

	@Column(name = "loyal_client", length = 45)
	public String getLoyalClient() {
		return this.loyalClient;
	}

	public void setLoyalClient(String loyalClient) {
		this.loyalClient = loyalClient;
	}

	@Column(name = "notes", length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopClients")
	public Set<Cars> getCarses() {
		return this.carses;
	}

	public void setCarses(Set<Cars> carses) {
		this.carses = carses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopClients")
	public Set<ClientInvoiceDetails> getClientInvoiceDetailses() {
		return this.clientInvoiceDetailses;
	}

	public void setClientInvoiceDetailses(Set<ClientInvoiceDetails> clientInvoiceDetailses) {
		this.clientInvoiceDetailses = clientInvoiceDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workshopClients")
	public Set<WorshopServices> getWorshopServiceses() {
		return this.worshopServiceses;
	}

	public void setWorshopServiceses(Set<WorshopServices> worshopServiceses) {
		this.worshopServiceses = worshopServiceses;
	}

}
