package com.repcar.viechlejob.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Services generated by hbm2java
 */
@Entity
@Table(name = "services", catalog = "repcar")
public class Services implements java.io.Serializable {

	private Integer serviceId;
	private ServiceCategories serviceCategories;
	private String serviceName;
	private int workshopServiceId;

	public Services() {
	}

	public Services(ServiceCategories serviceCategories, String serviceName, int workshopServiceId) {
		this.serviceCategories = serviceCategories;
		this.serviceName = serviceName;
		this.workshopServiceId = workshopServiceId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "service_id", unique = true, nullable = false)
	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "service_category_id", nullable = false)
	public ServiceCategories getServiceCategories() {
		return this.serviceCategories;
	}

	public void setServiceCategories(ServiceCategories serviceCategories) {
		this.serviceCategories = serviceCategories;
	}

	@Column(name = "service_name", nullable = false, length = 45)
	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	@Column(name = "workshop_service_id", nullable = false)
	public int getWorkshopServiceId() {
		return this.workshopServiceId;
	}

	public void setWorkshopServiceId(int workshopServiceId) {
		this.workshopServiceId = workshopServiceId;
	}

}
