package com.repcar.viechlejob.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ServiceCategories generated by hbm2java
 */
@Entity
@Table(name = "service_categories", catalog = "repcar")
public class ServiceCategories implements java.io.Serializable {

	private Integer categoryId;
	private String categoryName;
	private Set<UserDefinedServices> userDefinedServiceses = new HashSet<UserDefinedServices>(0);
	private Set<Services> serviceses = new HashSet<Services>(0);

	public ServiceCategories() {
	}

	public ServiceCategories(String categoryName, Set<UserDefinedServices> userDefinedServiceses,
			Set<Services> serviceses) {
		this.categoryName = categoryName;
		this.userDefinedServiceses = userDefinedServiceses;
		this.serviceses = serviceses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "category_name", length = 45)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceCategories")
	public Set<UserDefinedServices> getUserDefinedServiceses() {
		return this.userDefinedServiceses;
	}

	public void setUserDefinedServiceses(Set<UserDefinedServices> userDefinedServiceses) {
		this.userDefinedServiceses = userDefinedServiceses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "serviceCategories")
	public Set<Services> getServiceses() {
		return this.serviceses;
	}

	public void setServiceses(Set<Services> serviceses) {
		this.serviceses = serviceses;
	}

}
