package com.repcar.makemodel.beans;
// Generated May 2, 2017 2:05:10 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserSetting generated by hbm2java
 */
@Entity
@Table(name = "user_setting", catalog = "repcar", uniqueConstraints = @UniqueConstraint(columnNames = "user_nfc"))
public class UserSetting implements java.io.Serializable {

	private Integer userSettingId;
	private User user;
	private String userNfc;
	private String avatar;
	private String theme;
	private String local;
	private String language;

	public UserSetting() {
	}

	public UserSetting(User user, String userNfc) {
		this.user = user;
		this.userNfc = userNfc;
	}

	public UserSetting(User user, String userNfc, String avatar, String theme, String local, String language) {
		this.user = user;
		this.userNfc = userNfc;
		this.avatar = avatar;
		this.theme = theme;
		this.local = local;
		this.language = language;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_setting_id", unique = true, nullable = false)
	public Integer getUserSettingId() {
		return this.userSettingId;
	}

	public void setUserSettingId(Integer userSettingId) {
		this.userSettingId = userSettingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "user_nfc", unique = true, nullable = false)
	public String getUserNfc() {
		return this.userNfc;
	}

	public void setUserNfc(String userNfc) {
		this.userNfc = userNfc;
	}

	@Column(name = "avatar", length = 45)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "theme", length = 45)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@Column(name = "local", length = 45)
	public String getLocal() {
		return this.local;
	}

	public void setLocal(String local) {
		this.local = local;
	}

	@Column(name = "language", length = 45)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
